# STATISTICS CITED WITHIN TEXT OF PAPER ----------------------------------------
# statistics
rm(list = ls(pattern = "val"))
val.mepssamplesize <- formatC(nrow(fyc), big.mark = ",")
val.meaneducyr <- round(mean(fyc$educyr, na.rm = TRUE), 0)
val.pcnorxuse <-  round(100-100*mean(fyc$rxuse), 0)
val.meanrxuse <-  round(mean(fyc$rxuse), 2)
val.meanrxmc <-  round(mean(fyc$d_mc), 2)
val.proprxusediab <- round(nobs(diab.lm1)/nobs(diab.logit1), 2)
val.proprxusedepr <- round(nobs(depr.lm1)/nobs(depr.logit1), 2)
val.proprxusechol <- round(nobs(chol.lm1)/nobs(chol.logit1), 2)
val.blackame1 <- abs(round(ame1[1], 0))
val.hispame1 <- abs(round(ame1[2], 0))
val.educame1 <- abs(round(ame1[3]*4, 0))
val.blackexplained <- round(100*(ame1[1] - ame2[1])/ame1[1], 0)
val.hispexplained <- round(100*(ame1[2] - ame2[2])/ame1[2], 0)
val.educexplained <- round(100*(ame1[3] - ame2[3])/ame1[3], 0)
val.blackmcame <- abs(round(100*mc.logit1.ame["black"], 0))
val.hispmcame <- abs(round(100*mc.logit1.ame["hispanic"], 0))
val.educmcame <- 4*abs(round(100*mc.logit1.ame["educyr"], 0))
val.modobs <- formatC(nrow(fyc.m), big.mark = ",")
val.meandexplogit <- round(mean(fyc.m$rxuse), 2)
val.meandexppclogit <- round(100*mean(fyc.m$rxuse), 0)
val.medexplogitmean <- round(dexp.me.mean, 2)
val.medexplogithispmean <- round(coef(dexp.logit1)["hispanic"] * dexp.me.mean, 3)
val.iedexplogithispmean <- round(IeAtMean(coef(dexp.logit1)["hispanic"], mean(fyc.m$rxuse)), 3)
val.hisplogexpcoef <- round(coef(logexp.lm1)["hispanic"], 2)
val.educlogexpcoef <- round(100*coef(logexp.lm1)["educyr"]*4, 0)
val.medexplogiteducmean <- round(100*coef(dexp.logit1)["educyr"] * 4*dexp.me.mean,0)
val.hisplogexppc <- abs(round(100*(exp(coef(logexp.lm1)["hispanic"])- 1), 0))
val.predmean <-  round(pred[race == "White" & educyr == 12, pred], 0)
val.predcollege <- round(pred[race == "White" & educyr == 16, pred] - pred[race == "White" & educyr == 12, pred] , 0)
val.preddiffblack <- round(val.predmean - pred[race == "Black" & educyr == 16, pred])
val.preddiffhisp <-  round(val.predmean - pred[race == "Hispanic" & educyr == 16, pred])
val.iehispmclogitmean <- abs(round(100*IeAtMean(mc.logit1.coef["hispanic"], mean(fyc.m$d_mc)), 0))
val.iehispmcnbmean <- abs(round(mean(fyc.m$mc) * (exp(mcnum.nb1.coef["hispanic"])-1), 2))
val.meeducmclogitmean <- round(100*4*mc.logit1.coef["educyr"] * mc.me.mean)
val.meeducmcnbmean <- round(4*mcnum.nb1.coef["educyr"] * mean(fyc.m$mc),2)
val.iehispcdexplogitmean <- abs(round(100*IeAtMean(c.dexp.logit1.coef["hispanic"], mean(fyc.m$rxuse)), 0))
val.hispclogexppc <- abs(round(100*(exp(coef(c.logexp.lm1)["hispanic"])-1),0))
val.diabmean <-  round(mean(fyc.diab$rxexp_diab), 0)
val.cholmean <-  round(mean(fyc.chol$rxexp_chol), 0)
val.deprmean <- round(mean(fyc.depr$rxexp_depr), 0)
val.preddeprcollege <- round(pred.depr[race == "White" & educyr == 16, pred] - 
                         pred.depr[race == "White" & educyr == 12, pred], 0)
l.ch2stats <- setNames(lapply(ls(pattern="val"), function(x) get(x)), ls(pattern="val"))
ch2stats <- data.frame(do.call(rbind, l.ch2stats))
rownames(ch2stats) <- gsub("val.", "", rownames(ch2stats))

# output to text file to input into latex
ch2stats$def <-  "\\def"
names(ch2stats)[1] <- "value"
ch2stats$value <- as.character(ch2stats$value)
ch2stats <- data.frame(cbind(ch2stats$def, rownames(ch2stats), ch2stats$value))
ch2stats$output <- paste(ch2stats[, 1], " ", "\\", ch2stats[, 2],
                         "{", ch2stats[, 3], "}", sep = "")
fileConn <- file("output/ch2txtstats.txt")
writeLines(ch2stats$output, fileConn)
close(fileConn)
